import mongoose from 'mongoose';

const MONGODB_URI = "mongodb://huzaifa:amir@ac-80vfqnw-shard-00-00.3juvm8x.mongodb.net:27017,ac-80vfqnw-shard-00-01.3juvm8x.mongodb.net:27017,ac-80vfqnw-shard-00-02.3juvm8x.mongodb.net:27017/plant-disease-detector?ssl=true&replicaSet=atlas-52uo39-shard-0&authSource=admin&retryWrites=true&w=majority&appName=devops";

const DiseaseSchema = new mongoose.Schema({
  name: { type: String, required: true },
  description: { type: String, required: true },
  type: { type: String, enum: ['plant', 'tree'], required: true },
  symptoms: [{ type: String }],
  homemadeRemedies: { type: String },
  scientificRemedies: { type: String },
  pictures: [{ type: String }],
}, { timestamps: true });

const Disease = mongoose.models.Disease || mongoose.model('Disease', DiseaseSchema);

const moreDiseases = [
  // Plant Diseases (1-40)
  { name: 'Apple Scab', description: 'Fungal disease affecting apple trees, causing lesions on leaves and fruit.', type: 'tree', symptoms: ['Olive-green spots on leaves', 'Dark scabby spots on fruit', 'Yellowing leaves'], homemadeRemedies: 'Rake and destroy fallen leaves. Ensure good air circulation.', scientificRemedies: 'Apply fungicides containing myclobutanil or captan.' },
  { name: 'Anthracnose', description: 'Group of fungal diseases affecting shade trees and plants.', type: 'plant', symptoms: ['Irregular dead areas on leaves', 'Twig dieback', 'Cankers on branches'], homemadeRemedies: 'Prune infected areas. Keep plant foliage dry.', scientificRemedies: 'Chlorothalonil or copper-based fungicides.' },
  { name: 'Aster Yellows', description: 'Chronic systemic disease caused by a bacterium-like organism (phytoplasma) spread by leafhoppers.', type: 'plant', symptoms: ['Yellowing of young leaves', 'Stunted growth', 'Deformed green flowers'], homemadeRemedies: 'Remove and destroy infected plants immediately. Control leafhopper populations.', scientificRemedies: 'No chemical cure; focus on vector control using insecticides.' },
  { name: 'Bacterial Leaf Spot', description: 'Bacterial infection common in tomatoes, peppers, and ornamental plants.', type: 'plant', symptoms: ['Water-soaked spots on leaves', 'Yellow halos around spots', 'Defoliation'], homemadeRemedies: 'Avoid overhead watering. Remove infected plant debris.', scientificRemedies: 'Copper sprays applied early in the disease cycle.' },
  { name: 'Blossom End Rot', description: 'Physiological disorder caused by calcium deficiency, common in tomatoes and peppers.', type: 'plant', symptoms: ['Dark, sunken spots at the blossom end of fruit', 'Rotting fruit'], homemadeRemedies: 'Maintain consistent soil moisture. Add crushed eggshells to soil.', scientificRemedies: 'Calcium chloride foliar sprays.' },
  { name: 'Botrytis Blight (Gray Mold)', description: 'Fungal disease that attacks tender plant parts, common in humid conditions.', type: 'plant', symptoms: ['Fuzzy gray mold on blooms or fruit', 'Brown spotting on leaves', 'Stem cankers'], homemadeRemedies: 'Improve air circulation. Water at the base of the plant.', scientificRemedies: 'Fungicides like iprodione or chlorothalonil.' },
  { name: 'Clubroot', description: 'Soil-borne disease affecting the cabbage family (Brassicaceae).', type: 'plant', symptoms: ['Swollen, distorted roots', 'Wilting tops during hot days', 'Stunted growth'], homemadeRemedies: 'Raise soil pH by adding lime. Rotate crops.', scientificRemedies: 'Fungicide soil drenches (PCNB) where permitted.' },
  { name: 'Crown Gall', description: 'Bacterial disease causing tumor-like growths on roots and stems.', type: 'plant', symptoms: ['Woody galls on the stem near soil line', 'Stunted growth', 'Yellowing leaves'], homemadeRemedies: 'Destroy infected plants. Do not replant species in the same soil for years.', scientificRemedies: 'Preventive biological control using Agrobacterium radiobacter strain K84.' },
  { name: 'Damping Off', description: 'Fungal disease killing seedlings before or just after they emerge.', type: 'plant', symptoms: ['Seedlings collapse at the soil line', 'White mold on soil surface', 'Rotten roots'], homemadeRemedies: 'Use sterile potting soil. Avoid overwatering seedlings.', scientificRemedies: 'Seed treatments with thiram or captan.' },
  { name: 'Downy Mildew', description: 'Water mold disease affecting many vegetable and ornamental plants.', type: 'plant', symptoms: ['Yellow patches on upper leaf surface', 'Fluffy purplish growth on undersides', 'Leaf drop'], homemadeRemedies: 'Water early in the day. Space plants widely.', scientificRemedies: 'Mancozeb, chlorothalonil, or copper fungicides applied preventatively.' },
  { name: 'Early Blight', description: 'Fungal disease heavily affecting tomato and potato plants.', type: 'plant', symptoms: ['Target-like brown spots on older leaves', 'Yellowing surrounding spots', 'Stem lesions'], homemadeRemedies: 'Mulch around plants to prevent soil splashing. Stake plants.', scientificRemedies: 'Chlorothalonil or Mancozeb sprays.' },
  { name: 'Fire Blight', description: 'Destructive bacterial disease affecting apples, pears, and related species.', type: 'tree', symptoms: ['Shoots look burnt or scorched', 'Shepherd\'s crook shape on shoot tips', 'Oozing cankers'], homemadeRemedies: 'Prune infected branches 8-12 inches below visible damage. Disinfect tools.', scientificRemedies: 'Streptomycin sprays during bloom period.' },
  { name: 'Fusarium Wilt', description: 'Soil-borne fungal disease that enters through roots and blocks water-conducting vessels.', type: 'plant', symptoms: ['Wilting of leaves, often on one side', 'Yellowing of older leaves', 'Brown discoloration in stem tissue'], homemadeRemedies: 'Solarize soil. Remove infected plants completely.', scientificRemedies: 'No effective chemical cure once infected; plant resistant varieties.' },
  { name: 'Leaf Curl / Peach Leaf Curl', description: 'Fungal disease causing severe distortion of leaves on peach and nectarine trees.', type: 'tree', symptoms: ['Reddish, swollen, puckered leaves', 'Premature leaf drop', 'Reduced fruit yield'], homemadeRemedies: 'Clean up fallen leaves. Prune tree to improve air flow.', scientificRemedies: 'Dormant copper or chlorothalonil fungicidal spray in late winter.' },
  { name: 'Mosaic Virus', description: 'Viral disease affecting a huge variety of plants, often transmitted by aphids.', type: 'plant', symptoms: ['Mottled green and yellow leaves', 'Stunted growth', 'Distorted fruit'], homemadeRemedies: 'Remove and burn infected plants. Control aphid populations with insecticidal soap.', scientificRemedies: 'No chemical cure; rely on resistant varieties and pest control.' },
  { name: 'Rust Disease', description: 'Fungal disease producing rust-colored spores on various plants.', type: 'plant', symptoms: ['Orange, yellow or brown pustules on undersides of leaves', 'Yellow spots on upper surface', 'Leaf drop'], homemadeRemedies: 'Avoid wetting leaves. Remove infected leaves immediately.', scientificRemedies: 'Fungicides containing sulfur or neem oil.' },
  { name: 'Sclerotinia / White Mold', description: 'Fungal disease causing stem rot, heavily affecting beans, tomatoes, and sunflowers.', type: 'plant', symptoms: ['Water-soaked spots on stems', 'Cottony white growth on lesions', 'Hard black sclerotia inside stems'], homemadeRemedies: 'Increase plant spacing. Avoid excessive nitrogen fertilizer.', scientificRemedies: 'Fungicides like thiophanate-methyl or boscalid.' },
  { name: 'Sooty Mold', description: 'Black fungus that grows on honeydew excreted by sap-sucking insects.', type: 'plant', symptoms: ['Black, soot-like coating on leaves and stems', 'Reduced photosynthesis'], homemadeRemedies: 'Wash mold off with a strong stream of water. Control aphids, scale, or whiteflies.', scientificRemedies: 'Horticultural oils or insecticidal soaps to kill the insects producing honeydew.' },
  { name: 'Verticillium Wilt', description: 'Soil-borne fungal pathogen attacking over 300 plant species.', type: 'plant', symptoms: ['Wilting starting from the bottom leaves', 'V-shaped yellow lesions on leaf margins', 'Brown vascular tissue'], homemadeRemedies: 'Crop rotation. Solarize the soil.', scientificRemedies: 'Soil fumigation (rarely practical for homeowners). Use resistant varieties (V in seed codes).' },
  { name: 'Bacterial Wilt', description: 'Caused by bacteria that multiply rapidly inside the plant\'s water-conducting tissue.', type: 'plant', symptoms: ['Sudden wilting of the whole plant while still green', 'White sticky ooze from cut stems'], homemadeRemedies: 'Remove and destroy plants. Control cucumber beetles (the main vector).', scientificRemedies: 'No chemical cure. Insecticides to control cucumber beetles.' },
  
  // 21-40
  { name: 'Black Spot', description: 'Common fungal disease of roses.', type: 'plant', symptoms: ['Circular black spots with fringed edges on leaves', 'Yellowing leaves', 'Defoliation'], homemadeRemedies: 'Water at the base early in the day. Rake up fallen leaves.', scientificRemedies: 'Fungicides containing triforine or chlorothalonil.' },
  { name: 'Cedar Apple Rust', description: 'Fungal disease requiring two hosts (juniper and apple/crabapple).', type: 'tree', symptoms: ['Orange spots on apple leaves', 'Gall formations on junipers with orange jelly-like horns in spring'], homemadeRemedies: 'Remove nearby junipers/cedars. Prune out galls in winter.', scientificRemedies: 'Myclobutanil fungicide applied to apple trees in spring.' },
  { name: 'Chestnut Blight', description: 'Devastating fungal disease that wiped out the American chestnut.', type: 'tree', symptoms: ['Sunken cankers on bark', 'Wilting leaves above canker', 'Orange stromata on bark'], homemadeRemedies: 'Plant resistant hybrids.', scientificRemedies: 'Hypovirulence introduction (biological control).' },
  { name: 'Cypress Canker', description: 'Fungal disease affecting Leyland cypress and Monterey cypress.', type: 'tree', symptoms: ['Browning of branches from the top down', 'Resin oozing from bark cankers'], homemadeRemedies: 'Prune infected branches at least 4 inches below canker. Disinfect tools.', scientificRemedies: 'Copper fungicides can provide limited protection if applied early.' },
  { name: 'Phytophthora Root Rot', description: 'Water mold disease prevalent in poorly drained soils.', type: 'tree', symptoms: ['Yellowing foliage', 'Dieback of branches', 'Dark colored, rotting roots'], homemadeRemedies: 'Improve soil drainage. Avoid overwatering.', scientificRemedies: 'Fosetyl-Al or mefenoxam applied as soil drenches.' },
  { name: 'Oak Wilt', description: 'Aggressive fungal disease of oak trees.', type: 'tree', symptoms: ['Leaves turning brown from the tips inward', 'Rapid defoliation', 'Fungal mats under bark (red oaks)'], homemadeRemedies: 'Do not prune oaks in spring/summer. Trenching to sever root grafts.', scientificRemedies: 'Propiconazole trunk injections for prevention in high-risk areas.' },
  { name: 'Sudden Oak Death', description: 'Disease caused by the water mold Phytophthora ramorum.', type: 'tree', symptoms: ['Bleeding cankers on the trunk', 'Rapid browning of foliage', 'Dieback'], homemadeRemedies: 'Remove infected trees to slow spread. Clean tools and boots.', scientificRemedies: 'Phosphonate fungicide injections can act as a preventative.' },
  { name: 'Pine Wilt', description: 'Caused by the pinewood nematode, transmitted by pine sawyer beetles.', type: 'tree', symptoms: ['Fading of needles to yellow then brown', 'Complete tree death within weeks to months', 'Reduced resin flow'], homemadeRemedies: 'Remove and destroy infected trees rapidly to kill beetles/nematodes.', scientificRemedies: 'Emamectin benzoate trunk injections can prevent infection.' },
  { name: 'Needle Cast', description: 'Group of fungal diseases causing spruce and pine needles to turn brown and fall off.', type: 'tree', symptoms: ['Browning of inner needles', 'Black fruiting bodies on needles', 'Thinning canopy'], homemadeRemedies: 'Increase air circulation by thinning surroundings. Avoid wetting foliage.', scientificRemedies: 'Chlorothalonil applied when new growth is emerging.' },
  { name: 'Slime Flux (Wet Wood)', description: 'Bacterial infection of the inner wood of trees like elm, poplar, and oak.', type: 'tree', symptoms: ['Foul-smelling, bubbling liquid seeping from bark', 'Dark streaks on trunk', 'Insects attracted to ooze'], homemadeRemedies: 'No specific remedy; trees usually survive. Relieve pressure by drilling a drain hole (debated practice).', scientificRemedies: 'None.' },
  { name: 'Thousand Cankers Disease', description: 'Fungal disease spread by the walnut twig beetle, affecting walnut trees.', type: 'tree', symptoms: ['Yellowing and thinning of upper canopy', 'Tiny cankers under the bark', 'Twig dieback'], homemadeRemedies: 'Remove infected trees and burn or chip wood locally. Do not transport firewood.', scientificRemedies: 'No effective chemical controls currently.' },
  { name: 'Black Knot', description: 'Fungal disease affecting Prunus species (plum, cherry).', type: 'tree', symptoms: ['Hard, black, elongated galls on stems and branches', 'Branch dieback above galls'], homemadeRemedies: 'Prune out galls in winter, 4 inches below the swelling, and burn them.', scientificRemedies: 'Fungicides (captan or chlorothalonil) applied from bud break until shoot growth stops.' },
  { name: 'Cytospora Canker', description: 'Fungal canker disease attacking stressed fruit and shade trees.', type: 'tree', symptoms: ['Sunken, discolored bark', 'Amber-colored gummy ooze (on stone fruits)', 'Black pimple-like fruiting bodies'], homemadeRemedies: 'Keep trees healthy and watered. Prune infected limbs in dry weather.', scientificRemedies: 'No chemical control. Focus on sanitation and cultural practices.' },
  { name: 'Sycamore Anthracnose', description: 'Fungal disease specifically affecting American sycamore trees.', type: 'tree', symptoms: ['Dead areas along leaf veins', 'Twig dieback', 'Witches\' brooms (clusters of twigs)'], homemadeRemedies: 'Collect and destroy fallen leaves. Fertilize to promote vigor.', scientificRemedies: 'Systemic fungicides injected into the trunk in autumn or spring.' },
  { name: 'Leek Rust', description: 'Fungal disease of the allium family (onions, leeks, garlic).', type: 'plant', symptoms: ['Bright orange pustules on leaves', 'Leaves dying back prematurely', 'Reduced bulb size'], homemadeRemedies: 'Ensure good spacing. Do not grow alliums in the same spot consecutively.', scientificRemedies: 'Fungicides rarely needed for home growers; remove badly infected plants.' },
  { name: 'Tomato Spotted Wilt Virus', description: 'Viral disease spread by thrips.', type: 'plant', symptoms: ['Dark brown to purple spots on leaves', 'Bronzing of foliage', 'Ringspots on fruit'], homemadeRemedies: 'Control weeds that harbor thrips. Use reflective mulches.', scientificRemedies: 'Insecticides for thrips control; plant resistant varieties.' },
  { name: 'Pea Enation Mosaic Virus', description: 'Virus transmitted by aphids affecting peas and legumes.', type: 'plant', symptoms: ['Blister-like outgrowths (enations) on leaves/pods', 'Translucent windows in leaves', 'Stunted plants'], homemadeRemedies: 'Control aphids. Remove infected plants.', scientificRemedies: 'Insecticides targeting aphids. Use resistant varieties.' },
  { name: 'Onion White Rot', description: 'Devastating soil-borne fungal disease of alliums.', type: 'plant', symptoms: ['Yellowing and wilting of older leaves', 'Fluffy white fungus at the bulb base', 'Tiny black sclerotia in the fungus'], homemadeRemedies: 'Do not plant alliums in infected soil for up to 15 years. Strict hygiene.', scientificRemedies: 'Tebuconazole seed treatments (where permitted).' },
  { name: 'Potato Scab', description: 'Caused by a soil-dwelling bacterium-like organism (Streptomyces scabies).', type: 'plant', symptoms: ['Corky, rough lesions on potato tubers', 'Pitted spots'], homemadeRemedies: 'Lower soil pH to 5.0-5.2. Maintain consistent soil moisture during tuber formation.', scientificRemedies: 'Use certified disease-free seed potatoes. No highly effective chemical control.' },
  { name: 'Late Blight', description: 'The disease responsible for the Irish Potato Famine, caused by an oomycete.', type: 'plant', symptoms: ['Large, dark brown blotches on leaves with pale green edges', 'White mold underneath leaves in humid weather', 'Rotting potatoes'], homemadeRemedies: 'Destroy infected plants immediately. Do not compost them.', scientificRemedies: 'Chlorothalonil or copper applied preventatively; specialized fungicides for commercial use.' },

  // 41-60
  { name: 'Alternaria Leaf Spot', description: 'Fungal disease affecting many vegetables, notably brassicas.', type: 'plant', symptoms: ['Small, dark circular spots on leaves with concentric rings', 'Spots enlarge and merge', 'Leaf drop'], homemadeRemedies: 'Rotate crops. Treat seeds with hot water before planting.', scientificRemedies: 'Fungicides such as azoxystrobin or chlorothalonil.' },
  { name: 'Bacterial Speck', description: 'Bacterial disease primarily of tomatoes.', type: 'plant', symptoms: ['Tiny, dark brown to black spots on leaves', 'Yellow halos around spots', 'Tiny dark green spots on fruit'], homemadeRemedies: 'Avoid working around wet plants. Use disease-free seed.', scientificRemedies: 'Copper-based bactericides applied early.' },
  { name: 'Cercospora Leaf Spot', description: 'Fungal disease affecting beets, Swiss chard, and peppers.', type: 'plant', symptoms: ['Small, circular spots with light gray centers and dark borders', 'Leaves turning yellow and dying'], homemadeRemedies: 'Remove crop debris after harvest. Ensure good weed control.', scientificRemedies: 'Copper fungicides or mancozeb.' },
  { name: 'Cucumber Mosaic Virus', description: 'Virus with a very wide host range, not limited to cucumbers.', type: 'plant', symptoms: ['Mottling, wrinkling, and curling of leaves', 'Stunted plant growth', 'Pale, bumpy fruit'], homemadeRemedies: 'Control aphids. Eradicate perennial weed hosts.', scientificRemedies: 'No chemical control for the virus; manage vector insects.' },
  { name: 'Gummy Stem Blight', description: 'Fungal pathogen of cucurbits (melons, cucumbers, squash).', type: 'plant', symptoms: ['Brown, circular lesions on leaves', 'Stem cankers oozing a gummy, amber fluid', 'Black fruiting bodies on stems'], homemadeRemedies: 'Use a 2-3 year crop rotation. Avoid overhead irrigation.', scientificRemedies: 'Chlorothalonil mixed with thiophanate-methyl.' },
  { name: 'Galls (Various)', description: 'Abnormal outgrowths of plant tissues caused by insects, fungi, or bacteria.', type: 'tree', symptoms: ['Swollen areas on leaves, twigs, or roots', 'Oddly shaped protrusions'], homemadeRemedies: 'Prune out aesthetic galls. Most leaf galls are harmless to trees.', scientificRemedies: 'Specific to the cause; usually not necessary for established trees.' },
  { name: 'Halo Blight', description: 'Bacterial disease of beans.', type: 'plant', symptoms: ['Small water-soaked spots on leaves', 'Wide, greenish-yellow halos surrounding the spots', 'Reddish-brown spots on pods'], homemadeRemedies: 'Do not save seed from infected plants. Avoid overhead watering.', scientificRemedies: 'Copper-based sprays can reduce spread.' },
  { name: 'Leaf Spot (Septoria)', description: 'Fungal disease very common on tomatoes.', type: 'plant', symptoms: ['Numerous small, circular spots with dark borders and gray centers', 'Tiny black specks in the center of spots', 'Lower leaves die first'], homemadeRemedies: 'Remove lower leaves. Mulch to prevent soil splash.', scientificRemedies: 'Fungicides containing chlorothalonil.' },
  { name: 'Little Cherry Disease', description: 'Complex of viral/pathogenic diseases affecting sweet cherries.', type: 'tree', symptoms: ['Small, pale, unripened fruit', 'Fruit lacks flavor', 'Delayed maturity'], homemadeRemedies: 'Remove infected trees promptly to prevent spread via mealybugs.', scientificRemedies: 'No cure once infected. Control mealybug vectors.' },
  { name: 'Nectria Canker', description: 'Fungal disease causing cankers on hardwood trees including apple, pear, and maple.', type: 'tree', symptoms: ['Target-shaped cankers on twigs and branches', 'Small, red, raised fruiting bodies in autumn'], homemadeRemedies: 'Prune out cankers in dry weather. Avoid unnecessary wounding of the tree.', scientificRemedies: 'No effective fungicide.' },
  { name: 'Peach Scab', description: 'Fungal disease causing cosmetic damage to peaches.', type: 'tree', symptoms: ['Small, greenish-black spots on fruit near the stem end', 'Fruit may crack if severely infected', 'Olive spots on twigs'], homemadeRemedies: 'Prune for good air circulation.', scientificRemedies: 'Captan or chlorothalonil applied 2 weeks after shuck split.' },
  { name: 'Pecan Scab', description: 'Most destructive disease of pecan trees in moist climates.', type: 'tree', symptoms: ['Small, dark, circular spots on leaves and shucks', 'Nuts drop prematurely or fail to develop'], homemadeRemedies: 'Plant resistant varieties. Remove old shucks from trees.', scientificRemedies: 'Extensive fungicide program (e.g., propiconazole) from bud break through summer.' },
  { name: 'Plicaria Root Rot', description: 'Fungal root rot affecting coniferous seedlings.', type: 'tree', symptoms: ['Stunting, yellowing needles', 'Death of seedlings', 'Dark brown lesions on taproots'], homemadeRemedies: 'Improve nursery drainage.', scientificRemedies: 'Fungicide drenches in nursery settings.' },
  { name: 'Raspberry Cane Blight', description: 'Fungal disease entering through wounds on raspberry canes.', type: 'plant', symptoms: ['Dark brown cankers spreading down the cane', 'Wilting of fruitful canes in early summer', 'Wood becomes brittle'], homemadeRemedies: 'Prune out old fruiting canes immediately after harvest. Avoid injuring new canes.', scientificRemedies: 'Liquid copper applied in early spring.' },
  { name: 'Root Knot Nematodes', description: 'Microscopic worms that infect plant roots.', type: 'plant', symptoms: ['Stunted growth', 'Yellowing leaves (nutrient deficiency-like)', 'Distinctive swelling/knots on roots'], homemadeRemedies: 'Solarize soil. Plant nematode-suppressive French marigolds.', scientificRemedies: 'Nematicides applied to the soil prior to planting.' },
  { name: 'Smut', description: 'Fungal disease turning plant parts into powdery black masses; common on corn.', type: 'plant', symptoms: ['Large, whitish galls on ears or stalks of corn', 'Galls burst to release black powdery spores'], homemadeRemedies: 'Remove and burn galls before they burst. Grow resistant varieties.', scientificRemedies: 'Seed treatments can help prevent systemic smuts in grains.' },
  { name: 'Southern Blight', description: 'Fungal disease thriving in hot, humid weather, affecting hundreds of crops.', type: 'plant', symptoms: ['Sudden wilting of the entire plant', 'White fungal mat at the soil line', 'Mustard-seed-like round sclerotia'], homemadeRemedies: 'Deep plow the soil to bury sclerotia. Remove infected plants.', scientificRemedies: 'Fungicides such as penthiopyrad for commercial row crops.' },
  { name: 'Spur Blight', description: 'Fungal disease of red raspberries.', type: 'plant', symptoms: ['Brown or purple spots on stems at the buds (spurs)', 'Leaves on infected spurs turn yellow and fall', 'Decreased fruit yield'], homemadeRemedies: 'Keep weed growth low. Prune out old canes.', scientificRemedies: 'Lime-sulfur applied at the delayed dormant stage.' },
  { name: 'Strawberry Leaf Spot', description: 'Fungal infection common on strawberries.', type: 'plant', symptoms: ['Small, deep purple spots on upper leaf surfaces', 'Centers of spots turn white or gray', 'Reddish-purple borders'], homemadeRemedies: 'Remove infected leaves. Renew strawberry beds every few years.', scientificRemedies: 'Captan or copper fungicides.' },
  { name: 'Take-All Root Rot', description: 'Fungal disease affecting turfgrasses and wheat.', type: 'plant', symptoms: ['Irregular patches of yellowing or dead grass', 'Darkened, rotted roots', 'Stunted growth in wheat'], homemadeRemedies: 'Maintain proper soil pH (slightly acidic). Avoid excessive nitrogen fertilization.', scientificRemedies: 'Azoxystrobin or propiconazole fungicides for turf.' },

  // 61-80
  { name: 'Tar Spot', description: 'Cosmetic fungal disease of maple trees.', type: 'tree', symptoms: ['Large, raised black spots on leaves resembling tar drops', 'Pale yellow halos around spots', 'Minor premature defoliation'], homemadeRemedies: 'Rake and destroy fallen leaves in autumn.', scientificRemedies: 'Fungicides are rarely warranted due to minimal tree health impact.' },
  { name: 'Tobacco Mosaic Virus', description: 'Highly stable virus affecting tomatoes, peppers, and petunias.', type: 'plant', symptoms: ['Mottled light and dark green leaves', 'Fern-like curling of leaves', 'Stunted plants'], homemadeRemedies: 'Wash hands thoroughly with soap after using tobacco products before handling plants. Destroy infected plants.', scientificRemedies: 'None.' },
  { name: 'Bacterial Canker', description: 'Serious bacterial disease of stone fruits (cherry, plum, peach).', type: 'tree', symptoms: ['Cankers on branches oozing amber-colored gum', 'Dieback of branches', 'Brown spots on leaves falling out to leave "shot-holes"'], homemadeRemedies: 'Prune out cankers in summer when bacteria are less active. Disinfect tools.', scientificRemedies: 'Copper sprays in autumn and during dormant season.' },
  { name: 'Watermelon Mosaic Virus', description: 'Aphid-transmitted virus affecting squash, melons, and cucumbers.', type: 'plant', symptoms: ['Green mosaic patterns on leaves', 'Distorted, lumpy fruit', 'Stunting of vines'], homemadeRemedies: 'Use reflective mulches to deter aphids. Remove infected plants.', scientificRemedies: 'No chemical cure; control vectors.' },
  { name: 'White Pine Blister Rust', description: 'Devastating fungal disease of five-needle pines (e.g., Eastern White Pine).', type: 'tree', symptoms: ['Yellow spotting on needles', 'Swollen cankers on branches/trunk', 'Orange blister-like fruiting bodies erupting from bark'], homemadeRemedies: 'Remove the alternate host (Ribes species - currants/gooseberries) from the area. Prune lower branches.', scientificRemedies: 'No practical chemical control for mature trees.' },
  { name: 'Wood Decay / Heart Rot', description: 'Various fungi causing the internal decay of mature trees.', type: 'tree', symptoms: ['Mushroom or conk fruiting bodies on the trunk or roots', 'Hollow trunk', 'Branch failure'], homemadeRemedies: 'Avoid damaging tree bark with lawnmowers or trimmers. Ensure proper pruning cuts.', scientificRemedies: 'None; structural assessment of the tree may be necessary.' },
  { name: 'Yellow Tuft (Downy Mildew of Turfgrass)', description: 'Oomycete disease affecting turfgrasses.', type: 'plant', symptoms: ['Slightly stunted, yellow patches of grass', 'Dense clusters of dwarfed shoots (tufts)', 'White downy growth on leaves in mornings'], homemadeRemedies: 'Improve soil drainage. Avoid over-irrigation.', scientificRemedies: 'Mefenoxam or fosetyl-Al for severe cases.' },
  { name: 'Citrus Greening (Huanglongbing)', description: 'Devastating bacterial disease of citrus trees, spread by the Asian citrus psyllid.', type: 'tree', symptoms: ['Asymmetrical yellowing of leaves', 'Bitter, misshapen, green fruit', 'Dieback and eventual tree death'], homemadeRemedies: 'Remove infected trees immediately; there is no cure.', scientificRemedies: 'Intense vector (psyllid) control using systemic insecticides.' },
  { name: 'Brown Rot', description: 'Fungal disease affecting stone fruits.', type: 'tree', symptoms: ['Blossoms turn brown and wither', 'Rapid rotting of ripening fruit with powdery gray-brown tufts', 'Mummified fruit left on trees'], homemadeRemedies: 'Remove all mummified fruit during winter. Prune out infected twigs.', scientificRemedies: 'Apply fungicides (like myclobutanil) as blossoms open and again before harvest.' },
  { name: 'Plum Pox Virus (Sharka)', description: 'Most devastating viral disease of stone fruits worldwide.', type: 'tree', symptoms: ['Yellow or light green rings or lines on leaves', 'Deformed fruit with rings on the skin or pits', 'Premature fruit drop'], homemadeRemedies: 'Eradicate infected trees. Plant only certified virus-free trees.', scientificRemedies: 'None; strict quarantine and eradication are used.' },
  { name: 'Boxwood Blight', description: 'Rapidly spreading fungal disease of boxwood shrubs.', type: 'plant', symptoms: ['Dark brown leaf spots with darker borders', 'Black streaks on stems', 'Rapid defoliation'], homemadeRemedies: 'Clean up all fallen leaves completely. Do not introduce un-quarantined plants.', scientificRemedies: 'Preventative fungicide programs (chlorothalonil and propiconazole) require frequent application.' },
  { name: 'Coffee Leaf Rust', description: 'Fungal disease devastating to Arabica coffee plants.', type: 'tree', symptoms: ['Yellow-orange powdery spots on the undersides of leaves', 'Premature leaf drop', 'Severe reduction in berry yield'], homemadeRemedies: 'Maintain optimal plant nutrition and canopy management for airflow.', scientificRemedies: 'Copper-based fungicides applied before the rainy season.' },
  { name: 'Daylily Rust', description: 'Fungal disease of daylilies causing aesthetic damage.', type: 'plant', symptoms: ['Yellow-orange pustules on leaves', 'Yellow streaking', 'Browning and dying of foliage'], homemadeRemedies: 'Cut foliage to the ground in late autumn. Do not overhead water.', scientificRemedies: 'Alternating fungicides like chlorothalonil and myclobutanil.' },
  { name: 'Ergot', description: 'Fungal disease of rye and other cereals, producing toxic alkaloids.', type: 'plant', symptoms: ['Dark purple to black, hard, horn-like sclerotia replacing grains in the seed head', 'Honeydew secretion during flowering'], homemadeRemedies: 'Deep ploughing to bury sclerotia. Use clean seed.', scientificRemedies: 'Fungicides are rarely effective; management relies on cultural practices.' },
  { name: 'Onion Smudge', description: 'Fungal disease affecting white onions and leeks.', type: 'plant', symptoms: ['Dark green to black smudges on the outer scales of the bulb', 'Occurs mostly near the neck or root plate'], homemadeRemedies: 'Grow colored varieties (red or yellow) which have natural resistance. Cure bulbs properly before storage.', scientificRemedies: 'None typically required.' },
  { name: 'Pink Root', description: 'Soil-borne fungal disease of onions.', type: 'plant', symptoms: ['Roots turn light pink, then darken to red or purple, eventually dying', 'Stunted plant tops', 'Reduced bulb size'], homemadeRemedies: 'Solarize soil. Use long crop rotations (3-6 years). Plant resistant varieties.', scientificRemedies: 'Soil fumigation in severe commercial cases.' },
  { name: 'Rhizoctonia Web Blight', description: 'Fungal disease devastating in hot, humid climates.', type: 'plant', symptoms: ['Rapid blighting of leaves', 'Fungal webbing visible holding dead leaves to stems', 'Brown lesions'], homemadeRemedies: 'Ensure adequate spacing. Avoid overhead irrigation.', scientificRemedies: 'Fungicides such as azoxystrobin or flutolanil.' },
  { name: 'Silver Leaf', description: 'Fungal disease of broadleaf trees, especially Rosaceae family.', type: 'tree', symptoms: ['Leaves develop a silvery, metallic sheen', 'Branch dieback', 'Bracket fungi on dead wood'], homemadeRemedies: 'Prune branches back to healthy wood behind the brown staining in the wood. Paint large pruning cuts.', scientificRemedies: 'Trichoderma biological control products inserted into the trunk.' },
  { name: 'Rose Rosette Disease', description: 'Virus-like disease spread by microscopic eriophyid mites.', type: 'plant', symptoms: ['Excessive thorniness on new growth', 'Thick, clustered "witches broom" growth', 'Bright red foliage that does not turn green'], homemadeRemedies: 'Dig up and destroy the entire plant, including root system. Do not compost.', scientificRemedies: 'Miticides to control the vector, but no cure for the disease.' },
  { name: 'X-Disease', description: 'Phytoplasma disease transmitted by leafhoppers, affecting stone fruits.', type: 'tree', symptoms: ['Leaves roll upward and turn red or yellow', 'Shot-holes in leaves', 'Small, bitter, pointed fruit'], homemadeRemedies: 'Remove infected trees and chokecherry hosts nearby.', scientificRemedies: 'Vector control.' },
  { name: 'Zonate Leaf Spot', description: 'Fungal disease causing distinct bullseye spots on various plants including oaks and maples.', type: 'tree', symptoms: ['Large, pale leaf spots with concentric dark rings resembling a target'], homemadeRemedies: 'Rake and destroy fallen leaves to reduce overwintering spore populations.', scientificRemedies: 'Usually not necessary for mature trees; standard fungicides can be used on ornamentals.' }
];

async function seed80Diseases() {
  try {
    console.log('Connecting to MongoDB...');
    await mongoose.connect(MONGODB_URI);
    console.log('Connected to DB.');
    
    console.log(`Attempting to insert ${moreDiseases.length} new diseases...`);
    const result = await Disease.insertMany(moreDiseases);
    console.log(`Successfully inserted ${result.length} new cases into the database!`);
    
  } catch (error) {
    console.error('Error seeding database:');
    console.error(error);
  } finally {
    await mongoose.disconnect();
    console.log('Disconnected from MongoDB.');
  }
}

seed80Diseases();
